# Generated by Django 4.0.4 on 2022-05-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
