# Generated by Django 4.0.4 on 2022-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_todo_created_at_remove_todo_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todoItem',
        ),
    ]
